export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BERTH_NOT_FOUND: "BERTH_NOT_FOUND",
  BLOCKADE_NOT_FOUND: "BLOCKADE_NOT_FOUND",
  BLOCKADE_ALREADY_LIFTED: "BLOCKADE_ALREADY_LIFTED",
  BLOCKADE_WINDOW_INVALID: "BLOCKADE_WINDOW_INVALID"
} as const;
